# Generated by Django 4.0.1 on 2022-04-08 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutorapp', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegModel',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_Name', models.TextField(help_text='Enter full Name', max_length=100, null=True)),
                ('phone_number', models.BigIntegerField()),
                ('gender', models.CharField(default='gender', max_length=100, null=True)),
                ('Email', models.EmailField(help_text='Enter Email Address', max_length=100, null=True)),
                ('Password', models.CharField(help_text='Enter Password', max_length=10, null=True)),
                ('category', models.TextField(help_text='Enter category', null=True)),
                ('image', models.ImageField(default='image', null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
        migrations.CreateModel(
            name='userfeedbackmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Enter name', max_length=100)),
                ('email', models.CharField(help_text='Enter email', max_length=100, null=True)),
                ('phonenumber', models.BigIntegerField(help_text='Enter phone number')),
                ('description', models.CharField(help_text='Write description', max_length=300)),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorapp.tutorregmodel')),
            ],
            options={
                'db_table': 'feedback_users',
            },
        ),
        migrations.CreateModel(
            name='OrderDetailsModel',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateField(auto_now_add=True, null=True)),
                ('time_added', models.TimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='paid', max_length=100)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorapp.tutorcoursesmodel')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorapp.tutorregmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.userregmodel')),
            ],
            options={
                'db_table': 'order_details',
            },
        ),
    ]
