# Generated by Django 4.0.1 on 2022-01-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftbasketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craft_arts',
            name='Course_Fees',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='craft_arts',
            name='Tutor_id',
            field=models.IntegerField(),
        ),
    ]
